<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyKhachSan" Class="QLKSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-1M1S910\SQLEXPRESS;Initial Catalog=QuanLyKhachSan;Integrated Security=True" SettingsObjectName="BLLvsDAL.Properties.Settings" SettingsPropertyName="QuanLyKhachSanConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETHOADON" Member="CHITIETHOADONs">
    <Type Name="CHITIETHOADON">
      <Column Name="MAHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPHONG" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENPHONG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYKT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TIENDICHVU" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TIENLOAIPHONG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TIENMAUPHONG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TENNHANVIEN" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="HDON_CHITIETHOADON" Member="HDON" ThisKey="MAHD" OtherKey="MAHD" Type="HDON" IsForeignKey="true" />
      <Association Name="Phong_CHITIETHOADON" Member="Phong" ThisKey="MAPHONG" OtherKey="MaPhong" Type="Phong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOANNV" Member="TAIKHOANNVs">
    <Type Name="TAIKHOANNV">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TENTAIKHOAN" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PhanQuyen" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="NhanVien_TAIKHOANNV" Member="NhanVien" ThisKey="MANV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DichVu" Member="DichVus">
    <Type Name="DichVu">
      <Column Name="MaDV" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDV" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GiaDV" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="DichVu_PhieuDichVu" Member="PhieuDichVus" ThisKey="MaDV" OtherKey="MaDV" Type="PhieuDichVu" />
    </Type>
  </Table>
  <Table Name="dbo.DuLieu" Member="DuLieus">
    <Type Name="DuLieu">
      <Column Name="Stt" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DoTuoi" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ThuNhap" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SuDungDichVu" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MauPhong" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LoaiPhong" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="XacNhan" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HDON" Member="HDONs">
    <Type Name="HDON">
      <Column Name="MAHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGAYLAPHD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="HDON_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MAHD" OtherKey="MAHD" Type="CHITIETHOADON" />
      <Association Name="KhachHang_HDON" Member="KhachHang" ThisKey="MAKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HDON" Member="NhanVien" ThisKey="MANV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SoCMND" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="QuocTich" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="KhachHang_HDON" Member="HDONs" ThisKey="MaKH" OtherKey="MAKH" Type="HDON" />
      <Association Name="KhachHang_PhieuDichVu" Member="PhieuDichVus" ThisKey="MaKH" OtherKey="MaKH" Type="PhieuDichVu" />
      <Association Name="KhachHang_PHIEUTHUEPHONG" Member="PHIEUTHUEPHONGs" ThisKey="MaKH" OtherKey="MAKH" Type="PHIEUTHUEPHONG" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhong" Member="LoaiPhongs">
    <Type Name="LoaiPhong">
      <Column Name="MaLoaiPhong" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GiaPhong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="LoaiPhong_PhieuDangKy" Member="PhieuDangKies" ThisKey="MaLoaiPhong" OtherKey="MaLoaiPhong" Type="PhieuDangKy" />
      <Association Name="LoaiPhong_Phong" Member="Phongs" ThisKey="MaLoaiPhong" OtherKey="MaLoaiPhong" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.Luat" Member="Luats">
    <Type Name="Luat">
      <Column Name="Stt" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DoTuoi" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ThuNhap" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SuDungDichVu" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MauPhong" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LoaiPhong" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="XacNhan" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MauPhong" Member="MauPhongs">
    <Type Name="MauPhong">
      <Column Name="MaMauPhong" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenMauPhong" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="MauPhong_PhieuDangKy" Member="PhieuDangKies" ThisKey="MaMauPhong" OtherKey="MaMauPhong" Type="PhieuDangKy" />
      <Association Name="MauPhong_Phong" Member="Phongs" ThisKey="MaMauPhong" OtherKey="MaMauPhong" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SoCMND" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="NhanVien_TAIKHOANNV" Member="TAIKHOANNVs" ThisKey="MaNV" OtherKey="MANV" Type="TAIKHOANNV" />
      <Association Name="NhanVien_HDON" Member="HDONs" ThisKey="MaNV" OtherKey="MANV" Type="HDON" />
      <Association Name="NhanVien_PHIEUTHUEPHONG" Member="PHIEUTHUEPHONGs" ThisKey="MaNV" OtherKey="MANV" Type="PHIEUTHUEPHONG" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuDangKy" Member="PhieuDangKies">
    <Type Name="PhieuDangKy">
      <Column Name="MaPDK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaMauPhong" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MaLoaiPhong" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NgayVao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayTra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="QuocTich" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiPhong_PhieuDangKy" Member="LoaiPhong" ThisKey="MaLoaiPhong" OtherKey="MaLoaiPhong" Type="LoaiPhong" IsForeignKey="true" />
      <Association Name="MauPhong_PhieuDangKy" Member="MauPhong" ThisKey="MaMauPhong" OtherKey="MaMauPhong" Type="MauPhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuDichVu" Member="PhieuDichVus">
    <Type Name="PhieuDichVu">
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDV" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DichVu_PhieuDichVu" Member="DichVu" ThisKey="MaDV" OtherKey="MaDV" Type="DichVu" IsForeignKey="true" />
      <Association Name="KhachHang_PhieuDichVu" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUTHUEPHONG" Member="PHIEUTHUEPHONGs">
    <Type Name="PHIEUTHUEPHONG">
      <Column Name="MAPHONG" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYKETTHUC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="KhachHang_PHIEUTHUEPHONG" Member="KhachHang" ThisKey="MAKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_PHIEUTHUEPHONG" Member="NhanVien" ThisKey="MANV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
      <Association Name="Phong_PHIEUTHUEPHONG" Member="Phong" ThisKey="MAPHONG" OtherKey="MaPhong" Type="Phong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="MaPhong" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiPhong" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MaMauPhong" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="Phong_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MaPhong" OtherKey="MAPHONG" Type="CHITIETHOADON" />
      <Association Name="Phong_PHIEUTHUEPHONG" Member="PHIEUTHUEPHONGs" ThisKey="MaPhong" OtherKey="MAPHONG" Type="PHIEUTHUEPHONG" />
      <Association Name="LoaiPhong_Phong" Member="LoaiPhong" ThisKey="MaLoaiPhong" OtherKey="MaLoaiPhong" Type="LoaiPhong" IsForeignKey="true" />
      <Association Name="MauPhong_Phong" Member="MauPhong" ThisKey="MaMauPhong" OtherKey="MaMauPhong" Type="MauPhong" IsForeignKey="true" />
    </Type>
  </Table>
</Database>